Fixed spack package syntax
SeisSol/seissol-spack-aid pull request #10
Opened 2022-11-09 14:11 UTC by ravil-mobile

2022-11-10 14:12 UTC, Thomas-Ulrich approved these changes
(edit) I now unterstand the spec objects.

2022-11-10 14:12 UTC, Thomas-Ulrich commented on spack/packages/seissol-utils/package.py
> +            bins.append(paraview.previx.bin)
typo

2022-11-15 08:22 UTC, Thomas-Ulrich requested changes
```git='https://github.com/daisy20170101/SeisSol_Cookbook',```
does not exist any more.
(now https://github.com/SeisSol/Examples/ I guess)

2022-11-21 07:51 UTC, Thomas-Ulrich requested changes
Small changes

2022-11-21 07:51 UTC, Thomas-Ulrich commented on spack/packages/seissol-env/package.py
> +        pspamm = self.spec.dependencies(name='py-pspamm')[0]
You can also write 
```
pspamm = self.spec['py-pspamm']
```
https://spack.readthedocs.io/en/latest/packaging_guide.html#accessing-dependencies

2022-11-21 07:51 UTC, Thomas-Ulrich commented on spack/packages/seissol-utils/package.py
> +        gmsh = self.spec.dependencies(name='gmsh')[0]
```
pumgen = self.spec[pumgen']
gmsh = self.spec[gmsh']
```

2022-11-21 07:51 UTC, Thomas-Ulrich commented on spack/packages/seissol-utils/package.py
> +            paraview = self.spec.dependencies(name='paraview')[0]
paraview = self.spec[paraview']

2023-01-27 16:31 UTC, krenzland commented
@ravil-mobile What's the status of this PR?

2023-02-02 13:04 UTC, ravil-mobile commented
Hi @krenzland, I honestly cannot remember the current status. I guess I need to make changes suggested by Thomas and test it.

2023-03-28 07:58 UTC, Thomas-Ulrich commented
Hi, I've done the proposed changes. Maybe @ravil-mobile can validate and we can merge?

2023-03-28 11:00 UTC, merged

2023-03-28 13:16 UTC, krenzland commented
Thanks!